### ISSUE TITLE
stepdisc.calc on data frame

### ISSUE THREAD

**Issue by learning-freak** [MarekSlenker/MorphoTools2#1]
Hi,
The fuction `stepdisc.calc` doesnt work on data frame, for example I got error message when I use 
```
stepdisc.calc(iris)
Error in apply(object$data, 2, function(x) (abs(max(x) - min(x))) == 0) : 
  dim(X) must have a positive length
```

How can we fix it ?

**Comment by MarekSlenker** [comment]
Hi,
`stepdisc.calc()` function doesn't support data.frames. 
As any other functions from `MorphoTools2` package, it requires `morphodata` object, take a look to [data import section](https://github.com/MarekSlenker/MorphoTools2/wiki/2-Data-import,-checking-and-manipulation#data-import)  
You can work with `iris` dataset, but you have to add “ID”, “Population” and “Taxon” columns before original data, and read those data using `read.morphodata()` function.
Thanks for letting me know, I have to report error to user, that data frame (and other data types) is not supported.
